export const MSG = {
  REGISTER: 'REGISTER',
  CONFIG: 'CONFIG',
  REQUEST_PAIR_CANDIDATES: 'REQUEST_PAIR_CANDIDATES',
  PAIR: 'PAIR',
  UNPAIR: 'UNPAIR',
  ACTION: 'ACTION',
  AUTOMATION_RUN: 'AUTOMATION_RUN',
  AUTOMATION_SAVE: 'AUTOMATION_SAVE',
  AUTOMATION_LIST: 'AUTOMATION_LIST',
  AUTOMATION_DELETE: 'AUTOMATION_DELETE',
  DOMAIN_UPDATE: 'DOMAIN_UPDATE',
  LOG_REQUEST: 'LOG_REQUEST',
  PERMISSION_CHECK: 'PERMISSION_CHECK'
};
